### ISSUE TITLE
Please consider a more permissive license

### ISSUE THREAD

**Issue by aelse** [twitchscience/kinsumer#15]
Hi, I've been looking at the options for writing a kinesis worker in go without using the MultiLangDaemon feature of KCL. I've been considering using this library but the license (Amazon Software License) is a bit of a stumbling block.

The commit adding the license doesn't indicate why ASL was chosen. It's really meant for use by software released by Amazon or derived from Amazon's software. Is it possible that it was chosen because of the relation to the aws libraries in use? 

Using the kinesis library apis isn't a derivative work under the terms of the ASL by my reading ("...for the purposes of this License, derivative works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work").

Would you consider re-licensing under a more permissive license, perhaps either of the MIT or BSD licenses? This is a better fit as an open source project and means developers aren't constrained by the terms of the Amazon License which adds a bunch of rights in Amazon's favour to the code you wrote. Re-licensing would involve removing the current license files from the repository, adding the appropriate license information (depending on your choice of license) and adding a License section to the README.

Thanks for your consideration!

**Comment by garethlewin** [comment]
Hi.

Twitch is owned by Amazon, and as such we are required to release our open source software using the license that Amazon mandates us to use.
