### ISSUE TITLE
Travis build does not seem to be working correctly

### ISSUE THREAD

**Issue by mikemoate** [twitchscience/kinsumer#25]
Badge in README shows build status unknown and links to https://travis-ci.org/TwitchScience/kinsumer which reports "We couldn't find the repository 
TwitchScience/kinsumer".

https://github.com/twitchscience/kinsumer/commit/f4c965d5da6a5b4d472b4d84ec75b9ff1f5acddc is the last commit to have a travis build status flag (which links to https://travis-ci.org/twitchscience/kinsumer/builds/415983838?utm_source=github_status&utm_medium=notification).

**Comment by garethlewin** [comment]
Good catch, thanks, not sure what happened it's a casing issue https://travis-ci.org/twitchscience/kinsumer
