### ISSUE TITLE
What should user do when Next() returns an error?

### ISSUE THREAD

**Issue by bryanpaluch** [twitchscience/kinsumer#27]
We saw some sporadic errors committing "shard error (shardId-000000000015) in checkpointer.commit: error committing checkpoint: RequestError: send request failed
caused by: Post https://dynamodb.us-east-1.amazonaws.com/: read tcp 10.0.0.2:34560->52.94.0.96:443: read: connection reset by peer" and noticed that processing of the shard had stopped. It looks like the shard consumer stops processing when it receives a commit error. In the noop consumer there is a log Fatal which exits the application. What should a production app do? Is it safe to call Run() again and carry on processing with Next()? Is this a bug in the library?

**Comment by garethlewin** [comment]
No, sorry I should document this.

Kinsumer assumes that if Next() ever returns an error processing has stopped. I tend to build my services to exit in this case to get them to cycle in case an error repeats itself without a restart, but it is not required.

If you want your service to keep working, I recommend creating a new instance of kinsumer and processing that. The internal bookkeeping was much more complex if we wanted to allow Next() to work again.

**Comment by garethlewin** [comment]
Another thing you might want to look into is your aws sessions config's retry settings to maybe have the read from dynamo get retried.

**Comment by bryanpaluch** [comment]
thanks @GarethLewin I will do both.
