### ISSUE TITLE
Enhanced Fan-Out

### ISSUE THREAD

**Issue by nickpoorman** [twitchscience/kinsumer#36]
Thoughts on supporting enhanced fan-out? https://docs.aws.amazon.com/streams/latest/dev/introduction-to-enhanced-consumers.html

**Comment by garethlewin** [comment]
We have indeed considered it, but so far we haven't had someone directly ask for it. Part of the issue is working out how to keep the interface as simple as possible.

**Comment by MarkSRobinson** [comment]
I would personally use enhanced fan-out in my system
