### ISSUE TITLE
problem with using module in this package

### ISSUE THREAD

**Issue by brenol** [twitchscience/kinsumer#45]
Hi!

I have a few issues with the current uuid library, and even opened a issue in golang (#34432) and from what I gathered in that issue, the easiest fix is simply changing the uuid library.

I will open a PR changing it to google's UUID lib, as it pretty much works as-is and adding a go.mod file.

This is the error that is happening:
```
github.com/twitchscience/kinsumer imports
	github.com/twinj/uuid tested by
	github.com/twinj/uuid.test imports
	gopkg.in/stretchr/testify.v1/assert: cannot find module providing package gopkg.in/stretchr/testify.v1/assert
```

**Comment by garethlewin** [comment]
Thanks!
