### ISSUE TITLE
Issue reading kinesis stream across different aws accounts 

### ISSUE THREAD

**Issue by rhythmsharma** [twitchscience/kinsumer#48]
Hi,

I am trying to initialize a new Kinsumer Interface to read kinesis stream across different AWS accounts. I want to use different session and config credentials for it but not able to find any method which kinsumer supports currently. Could someone can guide how can I make use of Kinsumer to read streams across aws accounts. 
I have a kinesis client object as well. Can I make use of it to initialize kinsumer interface?

**Comment by garethlewin** [comment]
Hi @rhythmsharma you have two options.

The first is to create an aws-sdk-go session that uses sts to assume a role in the other account. Then youse the kinsumer method `NewWithSession` to initialize kinsumer with that session.

Alternatively, if you already have a kinesis client object you can create a dynamodb client object as well and call `NewWithInterfaces`

**Comment by rhythmsharma** [comment]
Thanks @GarethLewin for the response. `NewWithInterfaces` solves my purpose. I am able to initialize kinsumer using it.
