### ISSUE TITLE
Blocked at `.Next()`

### ISSUE THREAD

**Issue by jney** [twitchscience/kinsumer#55]
Here is a sample of our code we rewrote using kinsumer instead of https://github.com/harlow/kinesis-consumer.
It used to work using kinesis-consumer but we could only have one consumer per application.
Anyway, we wrote the following code but we are stuck at `k.Next()`, the last log `before next`

```go
	s := session.Must(session.NewSession(&aws.Config{
		Endpoint:   cfg.KinesisEndpoint,
		Region:     cfg.AWSRegion,
	}))
	config := kinsumer.NewConfig().
		WithThrottleDelay(time.Second).
		WithShardCheckFrequency(time.Second)
	k, _ := kinsumer.NewWithSession(s, streamName, fmt.Sprintf("%s_my_app", env), uuid.New().String(), config)
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			log.Info("before Next")
			k.Next()
			log.Info("inside Next")
		}
	}()
	wg.Wait()
```

Do someone have a any idea what we did wrong?
Thank you

**Comment by garethlewin** [comment]
You didn't call `Run()`. There is a simple sample app here https://github.com/twitchscience/kinsumer/blob/master/cmd/noopkinsumer/main.go

**Comment by garethlewin** [comment]
(Closed the issue because I believe this answers the question, if you have more questions feel free to reopen or make a new issue)
