### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by jeffcharles** [twitchscience/kinsumer#9]
Would it be possible to add some example code for using this library to the README or to a subdirectory?

**Comment by garethlewin** [comment]
https://github.com/TwitchScience/kinsumer/tree/master/cmd/noopkinsumer is intended to be the example, I need to be more specific and maybe write another example that includes production as part of the example.

**Comment by garethlewin** [comment]
@jeffcharles does noopkinsumer get you what you need?

**Comment by jeffcharles** [comment]
I guess it does for now. Will find out if it doesn't more as my project moves further along.
